### ISSUE TITLE
Left clicking on icon in system tray isn't doing anything

### ISSUE THREAD

**Issue by TentacleMonster** [crmarsh/discord-linux-bugs#116]
It should reopen the app, i suppose, but it does not. Right click is working fine, however.

**Comment by crmarsh** [comment]
The [docs](https://github.com/electron/electron/blob/master/docs/api/tray.md) indicated that you can't always use the click event on Linux, so I just put everything in the right click menu.

**Comment by ShayBox** [comment]
Well could you make it open the window for the DE's that do allow it (most of them) because i have to pin discord to my taskbar which is annoying when theres a tray icon right next to it

**Comment by ShayBox** [comment]
Add this. its required. even if all DE's don't have left clicking, most of them do, and for the ones that don't, that won't be able to click it anyway, make it easier for the people using KDE/XFCE and others. You already have the code working for right click, just add a listener for left, and make it do the same function as the top option on the right click menu

**Comment by crmarsh** [comment]
Sorry, let me clarify, I have registered a left click handler that opens the window. I found that this event was not being triggered on Linux, so **in addition** I added a right click menu option that does the same. Obviously the underlying system (often? always?) supports left click, so I don't actually know what electron's problem is here, but I also have failed to dedicate time to try to debug it myself because I found the workaround to be sufficient.
