### ISSUE TITLE
32-bit build for linux

### ISSUE THREAD

**Issue by RedstoneGeek223** [crmarsh/discord-linux-bugs#153]
Let me cut through the crap and get straight to the point... Being that I'm using 32-bit Linux (Kubuntu 16.10 x86) I have to use the web browser Version of discord however this is detrimental as most of my 4GB of memory is going to both a Minecraft server and a Minecraft client at the simultaneously, and the browser takes up precious memory. So if a 32-bit version (even if it doesn't get updated very often) could be released so that people who still have old computers (like me) can still play with and talk to their friends/teammates. 32-bit computers haven't been completely fazed out yet and most likely never will be, there some games only 32-bit computers can run efficiently, I own quite a few games that require a 32-bit OS and they run fine if I use one, but there are instances in which a 64-bit processor is just to fast. So it would be nice to have 32-bit Linux support just like Team Speak even though you say on the homepage for discord to ditch it, Which I may be tempted to return to if x86 Linux is not supported. possibly a duplicate of #56

**Comment by OvermindDL1** [comment]
A few things, I'm not related to discord, I'm just a heavy linux programmer:

> 4GB of memory is going to both a Minecraft server and a Minecraft client at the simultaneously

Assuming you are using no mods, otherwise that is dreadfully, dreadfully tiny, however the desktop version would use the same amount of ram as a single page as it is run in a standalone browser container (electron specifically if I recall correctly).

> So if a 32-bit version (even if it doesn't get updated very often) could be released so that people who still have old computers (like me) can still play with and talk to their friends/teammates. 32-bit computers haven't been completely fazed out yet and most likely never will be

What is your CPU?  It is highly unlikely any computer made in near the past decade does not support 64-bit if you are running an x86 arch (and if you are running a 32-bit arm arch then this is not a 32-bit request but a 32-bit arm request, is it?).

> there some games only 32-bit computers can run efficiently,

This, makes no sense?  If a 32-bit program is run on a 64-bit linux (or windows) then it runs in a 32-bit subsystem anyway.

> but there are instances in which a 64-bit processor is just to fast.

This especially makes no sense, no game should be CPU speed dependent since the old atari days, else the game would run differently on every machine.

**Comment by crmarsh** [comment]
See #56
