### ISSUE TITLE
Segfaulting still with `SIGSEGV in _XReply()`

### ISSUE THREAD

**Issue by glinton** [crmarsh/discord-linux-bugs#35]
0.0.7 still segfaulting in Ubuntu 16.04:
[stack trace `DiscordCanary crashed with SIGSEGV in _XReply()`](https://gist.github.com/glinton/5487266cf7b0021d3df51b1cc4f02987)
(reopen of #21)

**Comment by crmarsh** [comment]
Yeah, I see it in the crash logs now, I think i have a fix. Will be in 0.0.8.

If you're curious: the bug was that electron/chromium/whatever is also registering a x error handler, clobbering mine. Theirs expects to be called in some context I don't have or something and crashes. I've changed mine to just set and restore the x error handler during my function.
