### ISSUE TITLE
No visual notification on Arch + i3

### ISSUE THREAD

**Issue by JuanPotato** [crmarsh/discord-linux-bugs#69]
I am on Arch Linux using the i3 window manager, and when I get a new message, I only hear a sound notification and no visual notification. I have desktop notifications turned on.

**Comment by smasher816** [comment]
I have got notifications when running dunst. Have you tried testing the command "notify-send test" in a terminal? I feel like most programs use that same notification api.

**Comment by JuanPotato** [comment]
Nothing shows up, I also am using telegram which does show desktop notifications. Chromium also works.

**Comment by vhda** [comment]
Please try running `/usr/lib/notification-daemon/notification-daemon` manually.
I have had to add this to my startup script in order to have notifications in my icewm desktop.

**Comment by JuanPotato** [comment]
The file and folder do not exist on my machine.

**Comment by vhda** [comment]
Just remembered how great Arch's documentation is: https://wiki.archlinux.org/index.php/Desktop_notifications

**Comment by JuanPotato** [comment]
Ah, turns out I didn't have a notification server this whole time, well that's embarrassing. Thanks for your help.

**Comment by crmarsh** [comment]
Perhaps the Arch package should depend on libnotify if it doesn't already.

**Comment by vhda** [comment]
According to https://aur.archlinux.org/packages/discord-canary/ it already depends on libnotify, but it does not depend nor recommend a notification-daemon, which could improve the user experience.

But even if it did, the real problem here is that @JuanPotato is running i3, which is a minimalist window manager that does not implement a notification daemon and doesn't start such a daemon automatically. So he has to run a notification daemon from i3's startup scripts. Which daemon is obviously up to his personal preferences (the joy of running Linux!).
