### ISSUE TITLE
Desktop Entry - Icon path

### ISSUE THREAD

**Issue by Tadly** [crmarsh/discord-linux-bugs#91]
Currently the desktop entry uses an absolute path for its icon which does **not** work very nicely with icon-themes.

I'd like to see the path `/usr/share/pixmaps/discord-canary.png` to be replaced with a simple name like `discord`

**Comment by crmarsh** [comment]
Uh, that is what I put in the desktop file. Perhaps you have one from some other source? TBH, I don't fully understand the desktop file format, I just copied some example and messed with it until I got it working rather than learning about it. Here's my python function that generates the file:

```py
def generate_desktop_file(package_name, display_name, exe_name):
    desktop_file = [
        '[Desktop Entry]',
        'Name=' + display_name,
        'StartupWMClass=discord',
        "Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.",
        'GenericName=Internet Messenger',
        'Exec=/usr/share/' + package_name + '/' + exe_name,
        'Icon=' + package_name,
        'Type=Application',
        'StartupNotify=true',
        'Categories=Network;InstantMessaging;'
    ]
    return '\n'.join(desktop_file)
```

I welcome any suggestions on improvements. The name stuff is probably more complicated than it needs to be, but basically stems from having different build channels (like Canary and PTB) and different capitalizations.

**Comment by Tadly** [comment]
ahaaa you're right. The dude maintaining the archlinux aur package created his own desktop entry file.
I'll talk to him than.

Your method for creating the desktop-entry file looks good to me.
If you're interested in some specifics, here's the [freedesktop specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) for it. :)

**Comment by Tadly** [comment]
ahaaaa. slowly but surely I understand the issue.

This is what the aur package is based on
https://cdn-canary.discordapp.com/apps/linux/0.0.8/discord-canary-0.0.8.tar.gz

This doesn't include the .desktop entry file which is why the maintainer created
his own :)

Will you guys provide a proper `.deb` package at some point?

**Comment by crmarsh** [comment]
We do provide a [.deb file](https://discordapp.com/api/download/canary?platform=linux), but not an aur package. I didn't stick the desktop file into the tar.gz because it has an absolute path (on the Exec= line); The docs you linked claimed I should not need that, but when I tested it it didn't work without it.
